/** 指標說明。key 供 Stat / Help 元件查表，兩個頁面共用同一份文字。 */
export const HELP: Record<string, string> = {
  fps: '這一秒實際顯示到螢幕的幀數（SurfaceFlinger present-to-present），不是遊戲內部的渲染次數。',
  avg_fps: '總顯示幀數 ÷ 總時長，不是每秒 FPS 的平均，掉幀區段會按實際時長計入。',
  p90_session: '整段幀間隔累積到 90% 的值換算成 FPS，代表「最慢 10% 幀」的水準。即時頁的 P90 只看該秒。',
  low_1: '最慢 1% 幀的平均幀間隔換算成 FPS。比 P99 更接近卡頓感受，兩者差越大代表尾端越長。',
  p99_session: '同 P90 但累積到 99%，用來找出偶發的 micro-stutter。',
  p90: '這段期間幀間隔累積到 90% 的值換算成 FPS，代表「最慢 10% 幀」的水準。越接近 FPS 越穩。',
  p99: '同 P90 但累積到 99%，用來找出偶發的 micro-stutter。',
  dropped: 'SurfaceFlinger 判定未如期顯示的幀 ÷ 總幀數。',
  jank: '幀耗時 > 前 3 幀平均的 2 倍且 > 83ms 算 Jank，> 125ms 算 BigJank。即時模式用絕對門檻近似（標「近似」），與錄製模式的逐幀精確值不可直接比較。',
  jank_total: '本次 Session 累計的 Jank / BigJank 次數。',
  jank_10min: 'Jank 次數換算成每 10 分鐘的頻率，方便不同長度的 Session 比較。',
  stutter: '卡頓時長佔比：所有 Jank 幀的耗時總和 ÷ 總時長。',
  fps_std: '每秒 FPS 的標準差，越小越穩。',
  drop_fps: '相鄰兩秒 FPS 下降超過 8 的次數，用來找出「突然掉一截」的情況。',
  ftime: '幀間隔的平均與標準差（ms）。60 FPS 對應 16.7ms。',
  delta_ftime: '幀間隔超過 100ms 的幀數，每一幀都是感受得到的卡頓。',
  histogram: '幀間隔分布，區間不等距。越集中在左邊越穩，右邊出現長尾就是卡頓。',
  time_to_throttle: '從 Session 開始到 Thermal Status 首次達到 MODERATE 的秒數。壓力測試最重要的數字：撐多久才開始降頻。',
  throttle_duration: 'Thermal Status ≥ MODERATE 的累計秒數。',
  throttle: 'Android 的 Thermal Status：NONE → LIGHT → MODERATE → SEVERE → CRITICAL → EMERGENCY → SHUTDOWN。MODERATE 起系統會實質降頻。',
  temp_cpu: 'thermalservice 回報的 CPU 溫度，多顆感測器取最高（節流由最熱的那顆觸發）。',
  temp_gpu: 'GPU 溫度。thermalservice 沒有 GPU 型別的裝置改用 kgsl 的溫度節點。',
  temp_skin: '機身表面溫度，使用者實際摸到的溫度，也是多數廠商節流的依據。',
  temp_npu: 'NPU 溫度（thermalservice mType=9），沒有回報的裝置不顯示。',
  temp_stale: '溫度每 2 秒才讀一次，中間的取樣沿用上次的值，以較淡的顏色顯示。',
  cpu_app: '遊戲程序的 CPU 時間 × 核心數 ÷ 經過時間，演算法同 top，可超過 100%（8 核最高 800%）。',
  cpu_norm: 'App CPU × (目前頻率總和 ÷ 最高頻率總和)，把降頻的影響算進去；比較不同裝置或節流前後時用這個。',
  cpu_total: '整機所有核心的忙碌比例，0～100%。',
  cpu_freq: '各叢集的平均頻率（大核在前），取自 cpufreq 的 scaling_cur_freq，是 governor 設定值而非硬體實測；離線核心不計。',
  gpu_busy: 'GPU 忙碌比例。目前只有 Qualcomm Adreno 有可讀來源（kgsl gpubusy）；PowerVR、Mali 顯示 -。',
  gpu_freq: 'GPU 頻率。Qualcomm 取 kgsl clock_mhz，Pixel 取 devfreq cur_freq。',
  freq_chart: '每個核心一條線，依 cpuinfo_max_freq 分叢集：大核暖色、中核黃、小核綠，左軸 CPU MHz；GPU 頻率是右軸的藍線。0 代表核心離線。',
  gpu_mem: 'dumpsys gpu 回報的這個程序的 GPU 記憶體（貼圖、render buffer 等）。',
  pss: 'PSS：共用分頁按比例分攤後的實際佔用，Android 官方的記憶體指標。讀不到時改用 dumpsys meminfo 的 TOTAL PSS。',
  rss: 'RSS：常駐記憶體，共用分頁重複計算所以偏大。只在 PSS 讀不到時顯示。',
  swap: '已被置換到 zram／swap 的量。數字大代表整機記憶體吃緊，載入時可能因置換回來而卡頓。',
  mem_available: '整機目前可用的記憶體（MemAvailable）。',
  mem_detail: 'dumpsys meminfo 的分類（PSS）。Java Heap 是 Dalvik/ART；Native Heap 是 C/C++，Unity／Unreal 的資源主要在這；Code 是 .so／.dex；Graphics 與 GL mtrack 是 GPU 相關；System 是共用系統記憶體的分攤。',
  power: '電池電壓 × 電流，正值充電、負值放電。接著電源時是淨充電值，要拔線才有意義。',
  fpower: '每一幀的功耗：|功耗| ÷ FPS，單位 mW/幀。只在未接電源時計算。',
  wakeups: '區間內的 voluntary context switch 數，約等於執行緒被喚醒的次數。沒有絕對門檻，適合版本或場景間相對比較。',
  cswitch: '區間內的 context switch 總數（voluntary + nonvoluntary）。太高代表執行緒切換頻繁或鎖的競爭。',
  net: '整機所有網路介面的收／發速率。Android 12 起無 root 拿不到單一 App 的流量。',
  launch: 'am start -W 的 TotalTime：從 startActivity 到第一幀畫出來（Android 官方的 TTID）。冷啟動會先 force-stop。',
  package: 'Android 應用程式的套件名稱（例如 com.example.game）。按「偵測前景 App」會自動填入，也可從下拉清單挑選。',
  layer: '同一個遊戲可能有多個圖層（啟動畫面、廣告 WebView、SurfaceView）。「自動」挑幀數最多的；「列出圖層」會做一次 1.5 秒快照列出候選，只有前兩名幀數相近時才需要手動指定。',
  markers: '在時間軸上標記場景（例如「Boss 戰」），下方分段統計表會依標籤切段各自算 Avg／P90／Jank。',
  thresholds: '自訂門檻：超標的數字變橘色、圖上畫 FPS 下限線、下方列出超標區間。設定儲存在這個瀏覽器。',
  screenshot: '每 N 秒 screencap 一次，存在 Session 資料夾的 shots/。截圖會影響測到的數值，只在需要對照畫面時開。',
  record_mode: '用 Perfetto 擷取逐幀資料，停止後才能分析出精確的 Jank 與 App 層級歸因。錄製期間顯示的即時資料會在停止後被分析結果取代。',
  app_level: 'FrameTimeline 對 SurfaceView 的支援不完整，此時數字為顯示層級（SurfaceFlinger 實際顯示），Jank 歸因不可用。這是預期行為。',
  remove_sessions: '勾選要移除的 Session 後按右側「確認」。移除只是把資料夾搬到 sessions/removed/，不會刪除檔案；要釋放空間請手動刪除。',
  remove_confirm: '第一次按「確認」會再問一次，第二次才真的移除。按住 Shift 再按可跳過二次確認。',
  compare: '勾選同套件名稱的其他 Session 疊在同一張 FPS 圖上比較，最多 4 個。溫度線只畫主 Session 的。圖表可拖曳、滾輪縮放。',
  sys_chart: 'CPU 與 GPU 使用率用左軸（%），記憶體、功耗用右軸。功耗放大 100 倍（×100 mW）以便同軸。頻率見下方的頻率圖。',
  battery_level: '取自 dumpsys battery 的電量百分比，開始與結束各取一筆。',
  battery_charge: 'Charge counter 是電池 IC 累計的電荷量（mAh），開始減結束就是這段實際用掉的電量，比百分比精確。接著電源時可能為負。',
  battery_status: 'Android 回報的電池狀態（充電中／放電中／未充電／已充滿），取這段期間最常見的一個。',
  battery_chart_level: '電量百分比用左軸，電池溫度（thermalservice 的 BATTERY 型別）用右軸。',
  battery_chart_power: '電壓用左軸、電流用右軸，正值充電、負值放電。功耗 = 電壓 × 電流。',
  battery_chart_charge: 'Charge counter 是電池 IC 累計的電荷量，往下走就是在放電；階梯狀是 IC 的回報粒度。',
  total_frames: '這段期間實際顯示到螢幕的幀數總和。',
  duration: '從第一幀到最後一幀的時間長度。',
  fps_chart: 'FPS 與 P90 用左軸，溫度用右軸。色帶是 Thermal Status（黃 LIGHT／橘 MODERATE／紅 SEVERE 以上），紅點是 Jank，虛線是場景標籤與 FPS 門檻。溫度線變淡代表沿用上次讀數。',
}
